name: Neue Stadt hinzufügen
description: Füge eine neue Urban Sketchers Gruppe hinzu
title: "Neue Stadt: "
labels: ["neue-stadt"]
body:
  - type: markdown
    attributes:
      value: |
        Danke, dass du eine neue Urban Sketchers Gruppe hinzufügen möchtest!
        Bitte fülle die folgenden Felder aus.

  - type: input
    id: city
    attributes:
      label: Stadt
      description: Name der Stadt
      placeholder: z.B. Hamburg
    validations:
      required: true

  - type: input
    id: lat
    attributes:
      label: Breitengrad (lat)
      description: "Koordinaten findest du auf [latlong.net](https://www.latlong.net/)"
      placeholder: "z.B. 53.5511"
    validations:
      required: true

  - type: input
    id: lon
    attributes:
      label: Längengrad (lon)
      description: "Koordinaten findest du auf [latlong.net](https://www.latlong.net/)"
      placeholder: "z.B. 9.9937"
    validations:
      required: true

  - type: dropdown
    id: is_official
    attributes:
      label: Offizielles Chapter?
      description: Ist die Gruppe ein offizielles Urban Sketchers Chapter?
      options:
        - "Nein"
        - "Ja"
      default: 0

  - type: textarea
    id: description
    attributes:
      label: Treffpunkt & Zeiten
      description: Wann und wo trefft ihr euch? (optional)
      placeholder: "z.B. Treffen jeden 1. und 3. Sonntag im Monat, 11-14 Uhr"

  - type: input
    id: website
    attributes:
      label: Website
      description: URL zur eigenen Website (optional)
      placeholder: www.example.de

  - type: input
    id: email
    attributes:
      label: E-Mail
      description: Kontakt-E-Mail (optional)
      placeholder: kontakt@example.de

  - type: input
    id: facebook
    attributes:
      label: Facebook
      description: Link zur Facebook-Gruppe (optional)
      placeholder: https://facebook.com/groups/...

  - type: input
    id: instagram
    attributes:
      label: Instagram
      description: Instagram-Handle (optional)
      placeholder: "@usk_hamburg"

  - type: input
    id: bluesky
    attributes:
      label: Bluesky
      description: Bluesky-Handle (optional)
      placeholder: "@usk-hamburg.bsky.social"

  - type: input
    id: whatsapp
    attributes:
      label: WhatsApp
      description: Einladungslink zur WhatsApp-Gruppe (optional)
      placeholder: https://chat.whatsapp.com/...

  - type: checkboxes
    id: confirmation
    attributes:
      label: Bestätigung
      options:
        - label: Ich bin berechtigt, diese Gruppe hier zu listen
          required: true
