name: Stadt aktualisieren
description: Aktualisiere Infos einer bestehenden Urban Sketchers Gruppe
title: "Aktualisierung: "
labels: ["aktualisierung"]
body:
  - type: markdown
    attributes:
      value: |
        Hier kannst du die Infos einer bestehenden Gruppe aktualisieren.
        Fülle nur die Felder aus, die sich ändern sollen.

  - type: input
    id: city
    attributes:
      label: Stadt
      description: Welche Stadt möchtest du aktualisieren?
      placeholder: z.B. Bielefeld
    validations:
      required: true

  - type: input
    id: lat
    attributes:
      label: Breitengrad (lat)
      description: "Neuer Wert (leer = unverändert). [latlong.net](https://www.latlong.net/)"
      placeholder: "z.B. 53.5511"

  - type: input
    id: lon
    attributes:
      label: Längengrad (lon)
      description: "Neuer Wert (leer = unverändert). [latlong.net](https://www.latlong.net/)"
      placeholder: "z.B. 9.9937"

  - type: dropdown
    id: is_official
    attributes:
      label: Offizielles Chapter?
      description: Status ändern? (leer = unverändert)
      options:
        - ""
        - "Nein"
        - "Ja"
      default: 0

  - type: textarea
    id: description
    attributes:
      label: Treffpunkt & Zeiten
      description: Neuer Text (leer = unverändert, "entfernen" = Text löschen)
      placeholder: "z.B. Treffen jeden Sonntag, 11-14 Uhr"

  - type: input
    id: website
    attributes:
      label: Website
      description: Neue URL (leer = unverändert, "entfernen" = löschen)
      placeholder: www.example.de

  - type: input
    id: email
    attributes:
      label: E-Mail
      description: "Neue E-Mail (leer = unverändert, \"entfernen\" = löschen), auch mit Name: Max Mustermann <kontakt@example.de>"
      placeholder: kontakt@example.de

  - type: input
    id: facebook
    attributes:
      label: Facebook
      description: Neuer Link (leer = unverändert, "entfernen" = löschen)
      placeholder: https://facebook.com/groups/...

  - type: input
    id: instagram
    attributes:
      label: Instagram
      description: Neues Handle (leer = unverändert, "entfernen" = löschen)
      placeholder: "@usk_hamburg"

  - type: input
    id: bluesky
    attributes:
      label: Bluesky
      description: Neues Handle (leer = unverändert, "entfernen" = löschen)
      placeholder: "@usk-hamburg.bsky.social"

  - type: input
    id: whatsapp
    attributes:
      label: WhatsApp
      description: Neuer Link (leer = unverändert, "entfernen" = löschen)
      placeholder: https://chat.whatsapp.com/...

  - type: textarea
    id: reason
    attributes:
      label: Grund der Änderung
      description: Optional - warum wird aktualisiert?
      placeholder: z.B. Neue Treffzeiten ab Januar
